services:
    form.extension.jsonExtension:
        class: FE\testBundle\Form\Extension\Type\FormTypeJsonExtension
        tags:
            - { name: form.type_extension, extended_type: 'Symfony\Component\Form\Extension\Core\Type\FormType' }
