services:
    form.extension.jsonExtension:
        class: FE\testBundle\Form\Extension\Type\FormTypeJsonExtension
        arguments: ['@form.extension.jsonExtension.requestHandler']
        tags:
            - { name: form.type_extension, extended_type: 'Symfony\Component\Form\Extension\Core\Type\FormType' }
    form.type_extension.form.http_foundation:
        alias: form.extension.jsonExtension
    form.extension.jsonExtension.requestHandler:
        class: FE\testBundle\Form\Extension\JsonRequestHandler
        arguments: ['@form.type_extension.form.request_handler']
    form.extension.jsonExtension.listener:
        class: FE\testBundle\Form\Extension\JsonExtensionListener
        tags:
            - { name: kernel.event_subscriber }
